export const beautifulCities = [
    { "name": "Paris, France", "picture": "paris.jpg" },
    { "name": "Venice, Italy", "picture": "venice.jpg" },
    { "name": "Kyoto, Japan", "picture": "kyoto.jpg" },
    { "name": "Prague, Czech Republic", "picture": "prague.jpg" },
    { "name": "Barcelona, Spain", "picture": "barcelona.jpg" },
    { "name": "Cape Town, South Africa", "picture": "cape_town.jpg" },
    { "name": "Rio de Janeiro, Brazil", "picture": "rio_de_janeiro.jpg" },
    { "name": "Santorini, Greece", "picture": "santorini.jpg" },
    { "name": "Florence, Italy", "picture": "florence.jpg" },
    { "name": "Vancouver, Canada", "picture": "vancouver.jpg" },
    { "name": "Sydney, Australia", "picture": "sydney.jpg" },
    { "name": "Amsterdam, Netherlands", "picture": "amsterdam.jpg" },
    { "name": "Budapest, Hungary", "picture": "budapest.jpg" },
    { "name": "Edinburgh, Scotland", "picture": "edinburgh.jpg" },
    { "name": "Istanbul, Turkey", "picture": "istanbul.jpg" },
    { "name": "San Francisco, USA", "picture": "san_francisco.jpg" },
    { "name": "Dubrovnik, Croatia", "picture": "dubrovnik.jpg" },
    { "name": "Buenos Aires, Argentina", "picture": "buenos_aires.jpg" },
    { "name": "Petra, Jordan", "picture": "petra.jpg" },
    { "name": "Reykjavik, Iceland", "picture": "reykjavik.jpg" },
    { "name": "Marrakech, Morocco", "picture": "marrakech.jpg" },
    { "name": "Jaipur, India", "picture": "jaipur.jpg" },
    { "name": "Dubrovnik, Croatia", "picture": "dubrovnik2.jpg" },
    { "name": "Prague, Czech Republic", "picture": "prague2.jpg" },
    { "name": "Granada, Spain", "picture": "granada.jpg" },
    { "name": "Siem Reap, Cambodia", "picture": "siem_reap.jpg" },
    { "name": "Queenstown, New Zealand", "picture": "queenstown.jpg" },
    { "name": "Bruges, Belgium", "picture": "bruges.jpg" },
    { "name": "Charleston, USA", "picture": "charleston.jpg" },
    { "name": "Québec City, Canada", "picture": "quebec_city.jpg" },
    { "name": "St. Petersburg, Russia", "picture": "st_petersburg.jpg" },
    { "name": "Cape Town, South Africa", "picture": "cape_town2.jpg" },
    { "name": "Rio de Janeiro, Brazil", "picture": "rio_de_janeiro2.jpg" },
    { "name": "Salzburg, Austria", "picture": "salzburg.jpg" },
    { "name": "Kyoto, Japan", "picture": "kyoto2.jpg" },
    { "name": "Valletta, Malta", "picture": "valletta.jpg" },
    { "name": "Budapest, Hungary", "picture": "budapest2.jpg" },
    { "name": "Bergen, Norway", "picture": "bergen.jpg" },
    { "name": "Luang Prabang, Laos", "picture": "luang_prabang.jpg" },
    { "name": "Udaipur, India", "picture": "udaipur.jpg" },
    { "name": "Cartagena, Colombia", "picture": "cartagena.jpg" },
    { "name": "Chiang Mai, Thailand", "picture": "chiang_mai.jpg" },
    { "name": "Porto, Portugal", "picture": "porto.jpg" },
    { "name": "Florence, Italy", "picture": "florence2.jpg" },
    { "name": "Sydney, Australia", "picture": "sydney2.jpg" },
    { "name": "San Miguel de Allende, Mexico", "picture": "san_miguel_de_allende.jpg" },
    { "name": "Charleston, USA", "picture": "charleston2.jpg" },
    { "name": "Rome, Italy", "picture": "rome.jpg" },
    { "name": "Dubrovnik, Croatia", "picture": "dubrovnik3.jpg" },
    { "name": "Siem Reap, Cambodia", "picture": "siem_reap2.jpg" },
    { "name": "Kyoto, Japan", "picture": "kyoto3.jpg" },
    { "name": "Bora Bora, French Polynesia", "picture": "bora_bora.jpg" },
    { "name": "Cusco, Peru", "picture": "cusco.jpg" },
    { "name": "Quebec City, Canada", "picture": "quebec_city2.jpg" },
    // Add more cities as needed...
];

const games = [
    { "name": "The Legend of Zelda: Breath of the Wild", "picture": "zelda_breath_of_the_wild.jpg" },
    { "name": "The Witcher 3: Wild Hunt", "picture": "witcher_3.jpg" },
    { "name": "Grand Theft Auto V", "picture": "gta_v.jpg" },
    { "name": "Red Dead Redemption 2", "picture": "red_dead_redemption_2.jpg" },
    { "name": "Skyrim", "picture": "skyrim.jpg" },
    { "name": "Dark Souls III", "picture": "dark_souls_3.jpg" },
    { "name": "Bloodborne", "picture": "bloodborne.jpg" },
    { "name": "Super Mario Odyssey", "picture": "super_mario_odyssey.jpg" },
    { "name": "Persona 5", "picture": "persona_5.jpg" },
    { "name": "Horizon Zero Dawn", "picture": "horizon_zero_dawn.jpg" },
    { "name": "Mass Effect 2", "picture": "mass_effect_2.jpg" },
    { "name": "The Last of Us Part II", "picture": "the_last_of_us_2.jpg" },
    { "name": "Final Fantasy VII Remake", "picture": "final_fantasy_vii_remake.jpg" },
    { "name": "God of War (2018)", "picture": "god_of_war.jpg" },
    { "name": "Minecraft", "picture": "minecraft.jpg" },
    { "name": "Super Smash Bros. Ultimate", "picture": "super_smash_bros_ultimate.jpg" },
    { "name": "Overwatch", "picture": "overwatch.jpg" },
    { "name": "Fortnite", "picture": "fortnite.jpg" },
    { "name": "Call of Duty: Warzone", "picture": "cod_warzone.jpg" },
    { "name": "League of Legends", "picture": "league_of_legends.jpg" },
    { "name": "Valorant", "picture": "valorant.jpg" },
    { "name": "Among Us", "picture": "among_us.jpg" },
    { "name": "Animal Crossing: New Horizons", "picture": "animal_crossing_new_horizons.jpg" },
    { "name": "FIFA 21", "picture": "fifa_21.jpg" },
    { "name": "NBA 2K21", "picture": "nba_2k21.jpg" },
    { "name": "Rocket League", "picture": "rocket_league.jpg" },
    { "name": "Counter-Strike: Global Offensive", "picture": "csgo.jpg" },
    { "name": "World of Warcraft", "picture": "world_of_warcraft.jpg" },
    { "name": "Diablo III", "picture": "diablo_3.jpg" },
    { "name": "Civilization VI", "picture": "civilization_6.jpg" },
    { "name": "Stardew Valley", "picture": "stardew_valley.jpg" },
    { "name": "The Sims 4", "picture": "sims_4.jpg" },
    { "name": "Genshin Impact", "picture": "genshin_impact.jpg" },
    { "name": "Assassin's Creed Odyssey", "picture": "ac_odyssey.jpg" },
    { "name": "DOOM Eternal", "picture": "doom_eternal.jpg" },
    { "name": "Hades", "picture": "hades.jpg" },
    { "name": "Cyberpunk 2077", "picture": "cyberpunk_2077.jpg" },
    { "name": "Resident Evil Village", "picture": "resident_evil_village.jpg" },
    { "name": "Death Stranding", "picture": "death_stranding.jpg" },
    { "name": "Ghost of Tsushima", "picture": "ghost_of_tsushima.jpg" },
    { "name": "Mortal Kombat 11", "picture": "mortal_kombat_11.jpg" },
    { "name": "Marvel's Spider-Man", "picture": "spiderman.jpg" },
    { "name": "The Elder Scrolls Online", "picture": "eso.jpg" },
    { "name": "Sea of Thieves", "picture": "sea_of_thieves.jpg" },
    { "name": "Rainbow Six Siege", "picture": "rainbow_six_siege.jpg" },
    { "name": "Destiny 2", "picture": "destiny_2.jpg" },
    { "name": "Borderlands 3", "picture": "borderlands_3.jpg" },
    { "name": "The Outer Worlds", "picture": "outer_worlds.jpg" },
    { "name": "No Man's Sky", "picture": "no_mans_sky.jpg" },
    { "name": "Fallout 4", "picture": "fallout_4.jpg" },
    { "name": "Batman: Arkham Knight", "picture": "batman_arkham_knight.jpg" },
    { "name": "Tom Clancy's The Division 2", "picture": "the_division_2.jpg" },
    { "name": "Far Cry 5", "picture": "far_cry_5.jpg" },
    { "name": "Forza Horizon 4", "picture": "forza_horizon_4.jpg" },
    { "name": "Need for Speed Heat", "picture": "need_for_speed_heat.jpg" },
    { "name": "Super Mario Maker 2", "picture": "super_mario_maker_2.jpg" },
    { "name": "Pokémon Sword and Shield", "picture": "pokemon_sword_shield.jpg" },
    { "name": "Luigi's Mansion 3", "picture": "luigis_mansion_3.jpg" },
    { "name": "Mario Kart 8 Deluxe", "picture": "mario_kart_8_deluxe.jpg" },
    { "name": "Octopath Traveler", "picture": "octopath_traveler.jpg" },
    { "name": "Fire Emblem: Three Houses", "picture": "fire_emblem_three_houses.jpg" },
    { "name": "Super Mario Party", "picture": "super_mario_party.jpg" },
    { "name": "Ring Fit Adventure", "picture": "ring_fit_adventure.jpg" },
    { "name": "Splatoon 2", "picture": "splatoon_2.jpg" },
    { "name": "Dead Cells", "picture": "dead_cells.jpg" },
    { "name": "Celeste", "picture": "celeste.jpg" },
    { "name": "Hollow Knight", "picture": "hollow_knight.jpg" },
    { "name": "Undertale", "picture": "undertale.jpg" },
    { "name": "Cuphead", "picture": "cuphead.jpg" },
    { "name": "Shovel Knight", "picture": "shovel_knight.jpg" },
    { "name": "Into the Breach", "picture": "into_the_breach.jpg" },
    { "name": "Slay the Spire", "picture": "slay_the_spire.jpg" },
    { "name": "The Binding of Isaac: Rebirth", "picture": "binding_of_isaac.jpg" },
    { "name": "Hades", "picture": "hades2.jpg" },
    { "name": "Risk of Rain 2", "picture": "risk_of_rain_2.jpg" },
    { "name": "Dead by Daylight", "picture": "dead_by_daylight.jpg" },
    { "name": "Phasmophobia", "picture": "phasmophobia.jpg" },
    { "name": "Among Us", "picture": "among_us2.jpg" },
    { "name": "Fall Guys: Ultimate Knockout", "picture": "fall_guys.jpg" },
    { "name": "Among Us", "picture": "among_us3.jpg" },
    { "name": "Apex Legends", "picture": "apex_legends.jpg" },
    { "name": "Valorant", "picture": "valorant2.jpg" },
    { "name": "Call of Duty: Warzone", "picture": "cod_warzone2.jpg" },
    { "name": "Fortnite", "picture": "fortnite2.jpg" },
    { "name": "Overwatch", "picture": "overwatch2.jpg" },
    { "name": "League of Legends", "picture": "league_of_legends2.jpg" },
    { "name": "Minecraft", "picture": "minecraft2.jpg" },
    { "name": "FIFA 22", "picture": "fifa_22.jpg" },
    { "name": "NBA 2K22", "picture": "nba_2k22.jpg" },
    { "name": "Rocket League", "picture": "rocket_league2.jpg" },
    { "name": "Counter-Strike: Global Offensive", "picture": "csgo2.jpg" },
    { "name": "World of Warcraft", "picture": "world_of_warcraft2.jpg" },
    { "name": "Diablo IV", "picture": "diablo_iv.jpg" },
    { "name": "Civilization VII", "picture": "civilization_vii.jpg" },
    { "name": "The Sims 5", "picture": "sims_5.jpg" },
    { "name": "Genshin Impact", "picture": "genshin_impact2.jpg" },
    { "name": "Assassin's Creed: Valhalla", "picture": "ac_valhalla.jpg" },
    { "name": "DOOM Eternal", "picture": "doom_eternal2.jpg" },
    { "name": "Halo Infinite", "picture": "halo_infinite.jpg" },
    { "name": "Cyberpunk 2077", "picture": "cyberpunk_2077_2.jpg" },
    { "name": "Resident Evil Village", "picture": "resident_evil_village2.jpg" },
    { "name": "Death Stranding", "picture": "death_stranding2.jpg" },
    { "name": "Ghost of Tsushima", "picture": "ghost_of_tsushima2.jpg" },
    { "name": "Mortal Kombat 12", "picture": "mortal_kombat_12.jpg" },
    { "name": "Marvel's Spider-Man 2", "picture": "spiderman2.jpg" },
    { "name": "The Elder Scrolls VI", "picture": "elder_scrolls_vi.jpg" },
    { "name": "Sea of Thieves", "picture": "sea_of_thieves2.jpg" },
    { "name": "Rainbow Six Siege", "picture": "rainbow_six_siege2.jpg" },
    { "name": "Destiny 3", "picture": "destiny_3.jpg" },
    { "name": "Borderlands 4", "picture": "borderlands_4.jpg" },
    { "name": "The Outer Worlds 2", "picture": "outer_worlds2.jpg" },
    { "name": "No Man's Sky 2", "picture": "no_mans_sky2.jpg" },
    { "name": "Fallout 5", "picture": "fallout_5.jpg" },
    { "name": "Batman: Arkham Legacy", "picture": "batman_arkham_legacy.jpg" },
    { "name": "Tom Clancy's The Division 3", "picture": "the_division_3.jpg" },
    { "name": "Far Cry 6", "picture": "far_cry_6.jpg" },
    { "name": "Forza Horizon 5", "picture": "forza_horizon_5.jpg" },
    { "name": "Need for Speed 2023", "picture": "need_for_speed_2023.jpg" },
    { "name": "Super Mario Odyssey 2", "picture": "super_mario_odyssey2.jpg" },
    { "name": "Pokémon Brilliant Diamond/Shining Pearl", "picture": "pokemon_brilliant_diamond_shining_pearl.jpg" },
    { "name": "Luigi's Mansion 4", "picture": "luigis_mansion_4.jpg" },
    { "name": "Mario Kart 9", "picture": "mario_kart_9.jpg" },
    { "name": "Octopath Traveler 2", "picture": "octopath_traveler2.jpg" },
    { "name": "Fire Emblem: Four Houses", "picture": "fire_emblem_four_houses.jpg" },
    { "name": "Super Mario Party 2", "picture": "super_mario_party2.jpg" },
    { "name": "Ring Fit Adventure 2", "picture": "ring_fit_adventure2.jpg" },
    { "name": "Splatoon 3", "picture": "splatoon_3.jpg" },
    { "name": "Dead Cells 2", "picture": "dead_cells2.jpg" },
    { "name": "Celeste 2", "picture": "celeste2.jpg" },
    { "name": "Hollow Knight: Silksong", "picture": "hollow_knight_silksong.jpg" },
    { "name": "Undertale 2", "picture": "undertale2.jpg" },
    { "name": "Cuphead 2", "picture": "cuphead2.jpg" },
    { "name": "Shovel Knight 2", "picture": "shovel_knight2.jpg" },
    { "name": "Into the Breach 2", "picture": "into_the_breach2.jpg" },
    { "name": "Slay the Spire 2", "picture": "slay_the_spire2.jpg" },
    { "name": "The Binding of Isaac: Rebirth 2", "picture": "binding_of_isaac2.jpg" },
];


const anime = [
    {
        "name": "Naruto",
        "genre": ["Action", "Adventure"],
        "picture": "naruto.jpg"
    },
    {
        "name": "Attack on Titan",
        "genre": ["Action", "Fantasy"],
        "picture": "attack_on_titan.jpg"
    },
    {
        "name": "One Piece",
        "genre": ["Action", "Adventure"],
        "picture": "one_piece.jpg"
    },
    {
        "name": "Death Note",
        "genre": ["Mystery", "Thriller"],
        "picture": "death_note.jpg"
    },
    {
        "name": "Dragon Ball Z",
        "genre": ["Action", "Adventure"],
        "picture": "dragon_ball_z.jpg"
    },
    {
        "name": "Fullmetal Alchemist: Brotherhood",
        "genre": ["Action", "Adventure"],
        "picture": "fullmetal_alchemist_brotherhood.jpg"
    },
    {
        "name": "My Hero Academia",
        "genre": ["Action", "Super Power"],
        "picture": "my_hero_academia.jpg"
    },
    {
        "name": "Demon Slayer: Kimetsu no Yaiba",
        "genre": ["Action", "Supernatural"],
        "picture": "demon_slayer.jpg"
    },
    {
        "name": "Sword Art Online",
        "genre": ["Action", "Fantasy"],
        "picture": "sword_art_online.jpg"
    },
    {
        "name": "Tokyo Ghoul",
        "genre": ["Action", "Horror"],
        "picture": "tokyo_ghoul.jpg"
    },
    {
        "name": "Hunter x Hunter",
        "genre": ["Action", "Adventure"],
        "picture": "hunter_x_hunter.jpg"
    },
    {
        "name": "One Punch Man",
        "genre": ["Action", "Comedy"],
        "picture": "one_punch_man.jpg"
    },
    {
        "name": "Cowboy Bebop",
        "genre": ["Action", "Sci-Fi"],
        "picture": "cowboy_bebop.jpg"
    },
    {
        "name": "Steins;Gate",
        "genre": ["Thriller", "Sci-Fi"],
        "picture": "steins_gate.jpg"
    },
    {
        "name": "Neon Genesis Evangelion",
        "genre": ["Action", "Mecha"],
        "picture": "neon_genesis_evangelion.jpg"
    },
    {
        "name": "Code Geass",
        "genre": ["Action", "Mecha"],
        "picture": "code_geass.jpg"
    },
    {
        "name": "Fairy Tail",
        "genre": ["Action", "Adventure"],
        "picture": "fairy_tail.jpg"
    },
    {
        "name": "Death Parade",
        "genre": ["Psychological", "Mystery"],
        "picture": "death_parade.jpg"
    },
    {
        "name": "Your Lie in April",
        "genre": ["Drama", "Romance"],
        "picture": "your_lie_in_april.jpg"
    },
    {
        "name": "Clannad",
        "genre": ["Drama", "Romance"],
        "picture": "clannad.jpg"
    },
    {
        "name": "Violet Evergarden",
        "genre": ["Drama", "Slice of Life"],
        "picture": "violet_evergarden.jpg"
    },
    {
        "name": "Re:Zero - Starting Life in Another World",
        "genre": ["Drama", "Fantasy"],
        "picture": "re_zero.jpg"
    },
    {
        "name": "JoJo's Bizarre Adventure",
        "genre": ["Action", "Adventure"],
        "picture": "jojos_bizarre_adventure.jpg"
    },
    {
        "name": "Dragon Ball",
        "genre": ["Action", "Adventure"],
        "picture": "dragon_ball.jpg"
    },
    {
        "name": "Bleach",
        "genre": ["Action", "Supernatural"],
        "picture": "bleach.jpg"
    },
    {
        "name": "Black Clover",
        "genre": ["Action", "Magic"],
        "picture": "black_clover.jpg"
    },
    {
        "name": "Haikyuu!!",
        "genre": ["Sports", "Drama"],
        "picture": "haikyuu.jpg"
    },
    {
        "name": "Yuri on Ice",
        "genre": ["Sports", "Romance"],
        "picture": "yuri_on_ice.jpg"
    },
    {
        "name": "Kuroko's Basketball",
        "genre": ["Sports", "Comedy"],
        "picture": "kurokos_basketball.jpg"
    },
    {
        "name": "Attack on Titan",
        "genre": ["Action", "Fantasy"],
        "picture": "attack_on_titan2.jpg"
    },
    {
        "name": "One Piece",
        "genre": ["Action", "Adventure"],
        "picture": "one_piece2.jpg"
    },
    {
        "name": "Death Note",
        "genre": ["Mystery", "Thriller"],
        "picture": "death_note2.jpg"
    },
    {
        "name": "Dragon Ball Z",
        "genre": ["Action", "Adventure"],
        "picture": "dragon_ball_z2.jpg"
    },
    {
        "name": "Fullmetal Alchemist: Brotherhood",
        "genre": ["Action", "Adventure"],
        "picture": "fullmetal_alchemist_brotherhood2.jpg"
    },
    // Add more anime with their respective information...
];


const movies = [
    { "name": "Inception", "genre": ["Action", "Adventure", "Sci-Fi"] },
    { "name": "The Shawshank Redemption", "genre": ["Drama"] },
    { "name": "The Godfather", "genre": ["Crime", "Drama"] },
    { "name": "Pulp Fiction", "genre": ["Crime", "Drama"] },
    { "name": "Forrest Gump", "genre": ["Drama", "Romance"] },
    { "name": "The Dark Knight", "genre": ["Action", "Crime", "Drama"] },
    { "name": "The Matrix", "genre": ["Action", "Sci-Fi"] },
    { "name": "Fight Club", "genre": ["Drama"] },
    { "name": "Gladiator", "genre": ["Action", "Adventure", "Drama"] },
    { "name": "Schindler's List", "genre": ["Biography", "Drama", "History"] },
    { "name": "Saving Private Ryan", "genre": ["Drama", "War"] },
    { "name": "The Green Mile", "genre": ["Crime", "Drama", "Fantasy"] },
    { "name": "The Lord of the Rings: The Fellowship of the Ring", "genre": ["Adventure", "Drama", "Fantasy"] },
    { "name": "The Lord of the Rings: The Two Towers", "genre": ["Adventure", "Drama", "Fantasy"] },
    { "name": "The Lord of the Rings: The Return of the King", "genre": ["Adventure", "Drama", "Fantasy"] },
    { "name": "The Godfather: Part II", "genre": ["Crime", "Drama"] },
    { "name": "The Silence of the Lambs", "genre": ["Crime", "Drama", "Thriller"] },
    { "name": "The Usual Suspects", "genre": ["Crime", "Mystery", "Thriller"] },
    { "name": "Se7en", "genre": ["Crime", "Drama", "Mystery"] },
    { "name": "The Departed", "genre": ["Crime", "Drama", "Thriller"] },
    { "name": "Inglourious Basterds", "genre": ["Adventure", "Drama", "War"] },
    { "name": "The Prestige", "genre": ["Drama", "Mystery", "Sci-Fi"] },
    { "name": "The Lion King", "genre": ["Animation", "Adventure", "Drama"] },
    { "name": "Toy Story", "genre": ["Animation", "Adventure", "Comedy"] },
    { "name": "The Terminator", "genre": ["Action", "Sci-Fi"] },
    { "name": "Terminator 2: Judgment Day", "genre": ["Action", "Sci-Fi"] },
    { "name": "Goodfellas", "genre": ["Biography", "Crime", "Drama"] },
    { "name": "The Shining", "genre": ["Drama", "Horror"] },
    { "name": "The Sixth Sense", "genre": ["Drama", "Mystery", "Thriller"] },
    { "name": "Psycho", "genre": ["Horror", "Mystery", "Thriller"] },
    { "name": "Casablanca", "genre": ["Drama", "Romance", "War"] },
    { "name": "American Beauty", "genre": ["Drama", "Romance"] },
    { "name": "The Green Book", "genre": ["Biography", "Comedy", "Drama"] },
    { "name": "Avatar", "genre": ["Action", "Adventure", "Fantasy"] },
    { "name": "Jaws", "genre": ["Adventure", "Thriller"] },
    { "name": "Raiders of the Lost Ark", "genre": ["Action", "Adventure"] },
    { "name": "Jurassic Park", "genre": ["Action", "Adventure", "Sci-Fi"] },
    { "name": "Back to the Future", "genre": ["Adventure", "Comedy", "Sci-Fi"] },
    { "name": "The Wizard of Oz", "genre": ["Adventure", "Family", "Fantasy"] },
    { "name": "Titanic", "genre": ["Drama", "Romance"] },
    { "name": "E.T. the Extra-Terrestrial", "genre": ["Family", "Sci-Fi"] },
    { "name": "A Clockwork Orange", "genre": ["Crime", "Drama", "Sci-Fi"] },
    { "name": "The Exorcist", "genre": ["Horror"] },
    { "name": "The Sound of Music", "genre": ["Biography", "Drama", "Family"] },
    { "name": "Gone with the Wind", "genre": ["Drama", "History", "Romance"] },
    { "name": "The Godfather: Part III", "genre": ["Crime", "Drama"] },
    { "name": "Braveheart", "genre": ["Biography", "Drama", "History"] },
    { "name": "The Godfather: Part III", "genre": ["Crime", "Drama"] },
    { "name": "The Exorcist", "genre": ["Horror"] },
    { "name": "The Sound of Music", "genre": ["Biography", "Drama", "Family"] },
    { "name": "Gone with the Wind", "genre": ["Drama", "History", "Romance"] },
    { "name": "The Lord of the Rings: The Fellowship of the Ring", "genre": ["Adventure", "Drama", "Fantasy"] },
    { "name": "The Lord of the Rings: The Two Towers", "genre": ["Adventure", "Drama", "Fantasy"] },
    { "name": "The Lord of the Rings: The Return of the King", "genre": ["Adventure", "Drama", "Fantasy"] },
    { "name": "The Godfather: Part II", "genre": ["Crime", "Drama"] },
    { "name": "The Silence of the Lambs", "genre": ["Crime", "Drama", "Thriller"] },
    { "name": "The Usual Suspects", "genre": ["Crime", "Mystery", "Thriller"] },
    { "name": "Se7en", "genre": ["Crime", "Drama", "Mystery"] },
    { "name": "The Departed", "genre": ["Crime", "Drama", "Thriller"] },
    { "name": "Inglourious Basterds", "genre": ["Adventure", "Drama", "War"] },
    { "name": "The Prestige", "genre": ["Drama", "Mystery", "Sci-Fi"] },
    { "name": "The Lion King", "genre": ["Animation", "Adventure", "Drama"] },
    { "name": "Toy Story", "genre": ["Animation", "Adventure", "Comedy"] },
    { "name": "The Terminator", "genre": ["Action", "Sci-Fi"] },
    { "name": "Terminator 2: Judgment Day", "genre": ["Action", "Sci-Fi"] },
    { "name": "Goodfellas", "genre": ["Biography", "Crime", "Drama"] },
    { "name": "The Shining", "genre": ["Drama", "Horror"] },
    { "name": "The Sixth Sense", "genre": ["Drama", "Mystery", "Thriller"] },
    { "name": "Psycho", "genre": ["Horror", "Mystery", "Thriller"] },
    { "name": "Casablanca", "genre": ["Drama", "Romance", "War"] },
    { "name": "American Beauty", "genre": ["Drama", "Romance"] },
    { "name": "The Green Book", "genre": ["Biography", "Comedy", "Drama"] },
    { "name": "Avatar", "genre": ["Action", "Adventure", "Fantasy"] },
    { "name": "Jaws", "genre": ["Adventure", "Thriller"] },
    { "name": "Raiders of the Lost Ark", "genre": ["Action", "Adventure"] },
    { "name": "Jurassic Park", "genre": ["Action", "Adventure", "Sci-Fi"] },
    { "name": "Back to the Future", "genre": ["Adventure", "Comedy", "Sci-Fi"] },
    { "name": "The Wizard of Oz", "genre": ["Adventure", "Family", "Fantasy"] },
    { "name": "Titanic", "genre": ["Drama", "Romance"] },
    { "name": "E.T. the Extra-Terrestrial", "genre": ["Family", "Sci-Fi"] },
    { "name": "A Clockwork Orange", "genre": ["Crime", "Drama", "Sci-Fi"] },
    { "name": "The Exorcist", "genre": ["Horror"] },
    { "name": "The Sound of Music", "genre": ["Biography", "Drama", "Family"] },
    { "name": "Gone with the Wind", "genre": ["Drama", "History", "Romance"] },
    { "name": "The Godfather: Part III", "genre": ["Crime", "Drama"] },
    { "name": "Braveheart", "genre": ["Biography", "Drama", "History"] },
    // Add more movies with their respective "genre"s...
];
